# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSAGUI(object):
    def setupUi(self, RSAGUI):
        RSAGUI.setObjectName("RSAGUI")
        RSAGUI.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(RSAGUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_enc_dec = QtWidgets.QGroupBox(RSAGUI)
        self.group_enc_dec.setObjectName("group_enc_dec")
        self.enc_layout = QtWidgets.QVBoxLayout(self.group_enc_dec)
        self.enc_layout.setObjectName("enc_layout")
        self.label_plain = QtWidgets.QLabel(self.group_enc_dec)
        self.label_plain.setObjectName("label_plain")
        self.enc_layout.addWidget(self.label_plain)
        self.txt_plain_text = QtWidgets.QTextEdit(self.group_enc_dec)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.enc_layout.addWidget(self.txt_plain_text)
        self.label_cipher = QtWidgets.QLabel(self.group_enc_dec)
        self.label_cipher.setObjectName("label_cipher")
        self.enc_layout.addWidget(self.label_cipher)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.group_enc_dec)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.enc_layout.addWidget(self.txt_cipher_text)
        self.btn_layout_enc = QtWidgets.QHBoxLayout()
        self.btn_layout_enc.setObjectName("btn_layout_enc")
        self.btn_gen_keys = QtWidgets.QPushButton(self.group_enc_dec)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_layout_enc.addWidget(self.btn_gen_keys)
        self.btn_encrypt = QtWidgets.QPushButton(self.group_enc_dec)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_layout_enc.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.group_enc_dec)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_layout_enc.addWidget(self.btn_decrypt)
        self.enc_layout.addLayout(self.btn_layout_enc)
        self.verticalLayout.addWidget(self.group_enc_dec)
        self.group_sign_verify = QtWidgets.QGroupBox(RSAGUI)
        self.group_sign_verify.setObjectName("group_sign_verify")
        self.sign_layout = QtWidgets.QVBoxLayout(self.group_sign_verify)
        self.sign_layout.setObjectName("sign_layout")
        self.label_msg = QtWidgets.QLabel(self.group_sign_verify)
        self.label_msg.setObjectName("label_msg")
        self.sign_layout.addWidget(self.label_msg)
        self.txt_info = QtWidgets.QTextEdit(self.group_sign_verify)
        self.txt_info.setObjectName("txt_info")
        self.sign_layout.addWidget(self.txt_info)
        self.label_sign = QtWidgets.QLabel(self.group_sign_verify)
        self.label_sign.setObjectName("label_sign")
        self.sign_layout.addWidget(self.label_sign)
        self.txt_sign = QtWidgets.QTextEdit(self.group_sign_verify)
        self.txt_sign.setObjectName("txt_sign")
        self.sign_layout.addWidget(self.txt_sign)
        self.btn_layout_sign = QtWidgets.QHBoxLayout()
        self.btn_layout_sign.setObjectName("btn_layout_sign")
        self.btn_sign = QtWidgets.QPushButton(self.group_sign_verify)
        self.btn_sign.setObjectName("btn_sign")
        self.btn_layout_sign.addWidget(self.btn_sign)
        self.btn_verify = QtWidgets.QPushButton(self.group_sign_verify)
        self.btn_verify.setObjectName("btn_verify")
        self.btn_layout_sign.addWidget(self.btn_verify)
        self.sign_layout.addLayout(self.btn_layout_sign)
        self.verticalLayout.addWidget(self.group_sign_verify)

        self.retranslateUi(RSAGUI)
        QtCore.QMetaObject.connectSlotsByName(RSAGUI)

    def retranslateUi(self, RSAGUI):
        _translate = QtCore.QCoreApplication.translate
        RSAGUI.setWindowTitle(_translate("RSAGUI", "RSA Encryption Signing"))
        self.group_enc_dec.setTitle(_translate("RSAGUI", "Encryption / Decryption"))
        self.label_plain.setText(_translate("RSAGUI", "Plain Text"))
        self.label_cipher.setText(_translate("RSAGUI", "Cipher Text"))
        self.btn_gen_keys.setText(_translate("RSAGUI", "Generate Keys"))
        self.btn_encrypt.setText(_translate("RSAGUI", "Encrypt"))
        self.btn_decrypt.setText(_translate("RSAGUI", "Decrypt"))
        self.group_sign_verify.setTitle(_translate("RSAGUI", "Signing / Verification"))
        self.label_msg.setText(_translate("RSAGUI", "Message"))
        self.label_sign.setText(_translate("RSAGUI", "Signature"))
        self.btn_sign.setText(_translate("RSAGUI", "Sign"))
        self.btn_verify.setText(_translate("RSAGUI", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSAGUI = QtWidgets.QWidget()
    ui = Ui_RSAGUI()
    ui.setupUi(RSAGUI)
    RSAGUI.show()
    sys.exit(app.exec_())